// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsWorldAPI.Data;

#nullable disable

namespace SportsWorldAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251216134605_newMigrationNew")]
    partial class newMigrationNew
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("SportsWorldAPI.Models.Athlete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PurchaseStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Athletes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gender = "Male",
                            Image = "/images/JonJones.jpg",
                            Name = "Jon Jones",
                            Price = 30000000m,
                            PurchaseStatus = false
                        },
                        new
                        {
                            Id = 2,
                            Gender = "Female",
                            Image = "/images/AmandaNunes.jpg",
                            Name = "Amanda Nunes",
                            Price = 25000000m,
                            PurchaseStatus = false
                        },
                        new
                        {
                            Id = 3,
                            Gender = "Male",
                            Image = "/images/ConorMcGregor.jpeg",
                            Name = "Conor McGregor",
                            Price = 50000000m,
                            PurchaseStatus = false
                        },
                        new
                        {
                            Id = 4,
                            Gender = "Male",
                            Image = "/images/DanielCormier.jpg",
                            Name = "Daniel Cormier",
                            Price = 25000000m,
                            PurchaseStatus = false
                        },
                        new
                        {
                            Id = 5,
                            Gender = "Male",
                            Image = "/images/DonaldCerrone.jpg",
                            Name = "Donald Cerrone",
                            Price = 15000000m,
                            PurchaseStatus = false
                        },
                        new
                        {
                            Id = 6,
                            Gender = "Male",
                            Image = "/images/gsp.jpg",
                            Name = "Georges St-Pierre",
                            Price = 22000000m,
                            PurchaseStatus = false
                        },
                        new
                        {
                            Id = 7,
                            Gender = "Male",
                            Image = "/images/JoseAldo.jpg",
                            Name = "Jose Aldo",
                            Price = 19000000m,
                            PurchaseStatus = false
                        },
                        new
                        {
                            Id = 8,
                            Gender = "Male",
                            Image = "/images/KhabibNurmagomedov.webp",
                            Name = "Khabib Nurmagomedov",
                            Price = 27000000m,
                            PurchaseStatus = false
                        },
                        new
                        {
                            Id = 9,
                            Gender = "Male",
                            Image = "/images/MauricioRua.png",
                            Name = "Mauricio Rua",
                            Price = 17000000m,
                            PurchaseStatus = false
                        },
                        new
                        {
                            Id = 10,
                            Gender = "Female",
                            Image = "/images/RondaRousey.jpeg",
                            Name = "Ronda Rousey",
                            Price = 29000000m,
                            PurchaseStatus = false
                        },
                        new
                        {
                            Id = 11,
                            Gender = "Female",
                            Image = "/images/ValentinaShevchenko.jpg",
                            Name = "Valentina Shevchenko",
                            Price = 32000000m,
                            PurchaseStatus = false
                        },
                        new
                        {
                            Id = 12,
                            Gender = "Female",
                            Image = "/images/MackenzieDern.png",
                            Name = "Mackenzie Dern",
                            Price = 21000000m,
                            PurchaseStatus = false
                        });
                });

            modelBuilder.Entity("SportsWorldAPI.Models.Finance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoneyLeft")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoneySpent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfPurchases")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Finances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MoneyLeft = 10000000,
                            MoneySpent = 0,
                            NumberOfPurchases = 0
                        });
                });

            modelBuilder.Entity("SportsWorldAPI.Models.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 20000,
                            Image = "/images/venues/t-mobile-arena.jpg",
                            Name = "T-Mobile Arena"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 20789,
                            Image = "/images/venues/madison-square-garden.jpg",
                            Name = "Madison Square Garden"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 20000,
                            Image = "/images/venues/the-o2-arena.png",
                            Name = "The O2 Arena"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 18000,
                            Image = "/images/venues/etihad-arena.jpeg",
                            Name = "Etihad Arena"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 36500,
                            Image = "/images/venues/saitama-super-arena.jpg",
                            Name = "Saitama Super Arena"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 12000,
                            Image = "/images/venues/singapore-indoor-stadium.jpg",
                            Name = "Singapore Indoor Stadium"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 10000,
                            Image = "/images/venues/mohegan-sun-arena.png",
                            Name = "Mohegan Sun Arena"
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 15400,
                            Image = "/images/venues/jeunesse-arena.jpg",
                            Name = "Jeunesse Arena"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
